# Generated by Django 5.2.2 on 2025-06-04 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('source', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DataScienceNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Science News',
                'ordering': ['-publish_date', '-date_scraped'],
            },
        ),
    ]
