# Generated by Django 5.2.2 on 2025-06-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquote',
            options={'ordering': ['-date'], 'verbose_name': 'Citation du jour', 'verbose_name_plural': 'Citations du jour'},
        ),
        migrations.AlterModelOptions(
            name='datasciencenews',
            options={'ordering': ['-publish_date', '-date_scraped'], 'verbose_name': 'Actualité Data Science', 'verbose_name_plural': 'Actualités Data Science'},
        ),
        migrations.AddField(
            model_name='dailyquote',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=10),
        ),
    ]
